# Generated by Django 6.0 on 2025-12-16 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('message', models.TextField(blank=True)),
                ('source', models.CharField(default='web', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='accounts.dealerprofile')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='market.carlisting')),
            ],
            options={
                'indexes': [models.Index(fields=['dealer', '-created_at'], name='leads_inqui_dealer__40cdea_idx')],
            },
        ),
    ]
