# Generated by Django 6.0 on 2025-12-16 06:42

import django.db.models.deletion
import market.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(blank=True, max_length=180)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('region', models.CharField(blank=True, max_length=80)),
                ('country', models.CharField(default='Tanzania', max_length=80)),
                ('year', models.PositiveIntegerField()),
                ('make', models.CharField(max_length=60)),
                ('model', models.CharField(max_length=60)),
                ('trim', models.CharField(blank=True, max_length=60)),
                ('mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('fuel_type', models.CharField(choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel'), ('HYBRID', 'Hybrid'), ('ELECTRIC', 'Electric'), ('OTHER', 'Other')], default='PETROL', max_length=16)),
                ('transmission', models.CharField(choices=[('AUTO', 'Automatic'), ('MANUAL', 'Manual'), ('CVT', 'CVT'), ('OTHER', 'Other')], default='AUTO', max_length=16)),
                ('body_type', models.CharField(blank=True, max_length=40)),
                ('color', models.CharField(blank=True, max_length=40)),
                ('vin', models.CharField(blank=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('SOLD', 'Sold'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=16)),
                ('is_featured', models.BooleanField(default=False)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='accounts.dealerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=market.models.listing_image_path)),
                ('is_cover', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='market.carlisting')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='market.carlisting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='carlisting',
            index=models.Index(fields=['status', '-created_at'], name='market_carl_status_446640_idx'),
        ),
        migrations.AddIndex(
            model_name='carlisting',
            index=models.Index(fields=['make', 'model', 'year'], name='market_carl_make_231d5e_idx'),
        ),
        migrations.AddIndex(
            model_name='carlisting',
            index=models.Index(fields=['country', 'region', 'city'], name='market_carl_country_dc9813_idx'),
        ),
        migrations.AddIndex(
            model_name='carlisting',
            index=models.Index(fields=['price'], name='market_carl_price_3a9b71_idx'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'listing'), name='uniq_favorite_user_listing'),
        ),
    ]
