# Generated by Django 6.0 on 2025-12-16 08:13

import market.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=market.models.listing_thumb_path),
        ),
        migrations.AddConstraint(
            model_name='carimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_cover', True)), fields=('listing',), name='uniq_cover_per_listing'),
        ),
    ]
