# Generated by Django 6.0 on 2025-12-18 05:15

import django.db.models.deletion
import market.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('market', '0002_carimage_thumbnail_carimage_uniq_cover_per_listing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='market_cate_slug_44b033_idx')],
            },
        ),
        migrations.CreateModel(
            name='CategoryAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField()),
                ('label', models.CharField(max_length=100)),
                ('data_type', models.CharField(choices=[('int', 'int'), ('float', 'float'), ('text', 'text'), ('bool', 'bool'), ('choice', 'choice')], default='text', max_length=10)),
                ('is_filterable', models.BooleanField(default=True)),
                ('is_required', models.BooleanField(default=False)),
                ('choices', models.JSONField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='market.category')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(blank=True, max_length=180)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('region', models.CharField(blank=True, max_length=80)),
                ('country', models.CharField(default='Tanzania', max_length=80)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('SOLD', 'Sold'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=16)),
                ('is_featured', models.BooleanField(default=False)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='market.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_listings_v2', to=settings.AUTH_USER_MODEL)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings_v2', to='accounts.dealerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites_v2', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='market.listing')),
            ],
        ),
        migrations.CreateModel(
            name='ListingAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField()),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='market.categoryattribute')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='market.listing')),
            ],
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=market.models.listing_v2_image_path)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=market.models.listing_v2_thumb_path)),
                ('is_cover', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='market.listing')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='categoryattribute',
            index=models.Index(fields=['category', 'key'], name='market_cate_categor_dda474_idx'),
        ),
        migrations.AddConstraint(
            model_name='categoryattribute',
            constraint=models.UniqueConstraint(fields=('category', 'key'), name='uniq_category_attribute_key'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status', '-created_at'], name='market_list_status_dd503c_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['country', 'region', 'city'], name='market_list_country_62f9e5_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['price'], name='market_list_price_3a149f_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['category', 'status'], name='market_list_categor_da908a_idx'),
        ),
        migrations.AddConstraint(
            model_name='favoritev2',
            constraint=models.UniqueConstraint(fields=('user', 'listing'), name='uniq_favorite_user_listing_v2'),
        ),
        migrations.AddIndex(
            model_name='listingattributevalue',
            index=models.Index(fields=['attribute'], name='market_list_attribu_938619_idx'),
        ),
        migrations.AddIndex(
            model_name='listingattributevalue',
            index=models.Index(fields=['listing'], name='market_list_listing_bd11c5_idx'),
        ),
        migrations.AddConstraint(
            model_name='listingattributevalue',
            constraint=models.UniqueConstraint(fields=('listing', 'attribute'), name='uniq_listing_attribute_value'),
        ),
        migrations.AddConstraint(
            model_name='listingimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_cover', True)), fields=('listing',), name='uniq_cover_per_listing_v2'),
        ),
    ]
