# Generated by Django 5.2.9 on 2025-12-30 20:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('market', '0003_category_categoryattribute_listing_favoritev2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carlisting',
            name='moderation_status',
            field=models.CharField(choices=[('PENDING', 'Pending review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=16),
        ),
        migrations.AddField(
            model_name='carlisting',
            name='plate_number',
            field=models.CharField(blank=True, db_index=True, help_text='Vehicle registration/plate number. Required for publishing vehicles.', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='carlisting',
            name='plate_photo',
            field=models.ImageField(blank=True, help_text='Photo showing the plate (manual review).', null=True, upload_to='listings/plates/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='moderation_status',
            field=models.CharField(choices=[('PENDING', 'Pending review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', help_text='Manual moderation for fraud/duplicate control.', max_length=16),
        ),
        migrations.AddField(
            model_name='listing',
            name='plate_number',
            field=models.CharField(blank=True, db_index=True, help_text='Vehicle registration/plate number. Required for vehicles before publishing.', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='plate_photo',
            field=models.ImageField(blank=True, help_text='Photo showing the plate. Required for vehicles before publishing.', null=True, upload_to='listings/v2/plates/'),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='image',
            field=models.ImageField(upload_to='listings/images/'),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='listings/thumbs/'),
        ),
        migrations.AddIndex(
            model_name='carlisting',
            index=models.Index(fields=['plate_number'], name='market_carl_plate_n_3d4a71_idx'),
        ),
        migrations.AddIndex(
            model_name='carlisting',
            index=models.Index(fields=['moderation_status', 'status'], name='market_carl_moderat_7dea1e_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['plate_number'], name='market_list_plate_n_ba524a_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['moderation_status', 'status'], name='market_list_moderat_bd1e60_idx'),
        ),
        migrations.AddConstraint(
            model_name='carlisting',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PUBLISHED'), ('plate_number__isnull', False)), fields=('plate_number',), name='uniq_published_plate_number_v1'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PUBLISHED'), ('plate_number__isnull', False)), fields=('plate_number',), name='uniq_published_plate_number_v2'),
        ),
    ]
